{{- if and (eq .Values.storage.type "local") (not .Values.storage.local.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nexspence.fullname" . }}-blobs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexspence.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.local.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.local.size }}
  {{- with .Values.storage.local.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
