package alpine

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// realPKGInfo mirrors the exact .PKGINFO content of a real curl-8.22.0-r0.apk
// downloaded from dl-cdn.alpinelinux.org during live verification.
const realPKGInfo = `# Generated by abuild 3.17.0-r0
# using fakeroot version 1.37.2
pkgname = curl
pkgver = 8.22.0-r0
pkgdesc = URL retrieval utility and library
url = https://curl.se/
builddate = 1788359140
packager = Buildozer <alpine-devel@lists.alpinelinux.org>
size = 285023
arch = x86_64
origin = curl
commit = ab53c408436ac7199ed5b67bde204aaca73003bd
maintainer = Achill Gilgenast <achill@achill.org>
license = curl
replaces = wcurl
depend = libcurl=8.22.0-r0
provides = wcurl=8.22.0-r0
# automatically detected:
provides = cmd:curl=8.22.0-r0
provides = cmd:wcurl=8.22.0-r0
depend = so:libc.musl-x86_64.so.1
depend = so:libcurl.so.4
depend = so:libz.so.1
datahash = c8a90959b98efb93b866181155f89cc6206c7e33b66d9323a87ff6370114ee40
`

func TestDecodePKGInfo_RealCurlFixture(t *testing.T) {
	info := decodePKGInfo(realPKGInfo)
	assert.Equal(t, "curl", info.Name)
	assert.Equal(t, "8.22.0-r0", info.Version)
	assert.Equal(t, "URL retrieval utility and library", info.Description)
	assert.Equal(t, "curl", info.License)
	assert.Equal(t, int64(285023), info.InstalledSize)
	assert.ElementsMatch(t, []string{"libcurl=8.22.0-r0", "so:libc.musl-x86_64.so.1", "so:libcurl.so.4", "so:libz.so.1"}, info.Depends)
	assert.ElementsMatch(t, []string{"wcurl=8.22.0-r0", "cmd:curl=8.22.0-r0", "cmd:wcurl=8.22.0-r0"}, info.Provides)
}

func TestParsePKGInfo_FromRealControlTar(t *testing.T) {
	control := tarWith(t, ".PKGINFO", []byte(realPKGInfo))
	info, err := parsePKGInfo(control)
	require.NoError(t, err)
	assert.Equal(t, "curl", info.Name)
	assert.Equal(t, "8.22.0-r0", info.Version)
}

func TestParsePKGInfo_MissingEntry(t *testing.T) {
	control := tarWith(t, "some-other-file", []byte("irrelevant"))
	_, err := parsePKGInfo(control)
	assert.Error(t, err)
}

func TestParsePKGInfo_MissingPkgnameOrPkgver(t *testing.T) {
	control := tarWith(t, ".PKGINFO", []byte("pkgdesc = only a description\n"))
	_, err := parsePKGInfo(control)
	assert.Error(t, err, "a .PKGINFO without pkgname/pkgver must not be treated as authoritative")
}
